In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
pi = 3.141592
r = 6371
2*r*pi

40030.165264

In [ ]:
import numpy as np

np.cos(3.14)

-0.9999987317275395

In [ ]:
from numpy import cos as ppp

ppp(3.14)

-0.9999987317275395

In [ ]:
np.sin(pi/3) + np.cos(pi/3)

1.3660254835278955

In [ ]:
np.arcsin(-0.3) + np.arccos(0.3)

0.9614110187641016

In [ ]:
a = 3
a = 3.4
type(a)
#print(a)

float

In [ ]:
radius = 4.53
state = radius ** 2 * pi / 12
print(state)

5.3723579394000005


In [ ]:
money = 1000000 * 1.019 * 1.019
print(money)

1038360.9999999998


In [ ]:
s = 3.4
v = str(s)
type(v)

str

In [ ]:
v + 'korea'

'3.4korea'

In [ ]:
print(f'value of v is {v}')

value of v is 3.4


In [ ]:
v = 0.5

In [ ]:
import numpy as np
s = np.sin(0.5)
c = np.cos(0.5)
print(s+c)
print(s-c)

1.3570081004945758
-0.39815702328616975


In [ ]:
year = 2022
month = 4
day = 5
print(f'{year}년 {month}월 {day}일')

2022년 4월 5일


In [ ]:
import numpy as np
a = np.sin(np.pi/3)
print(f'결과는 {a:.2f} 입니다')
print('사인값은 양수', end='')
if a > 0:
  print('입니다.')
else:
  print('가 아닙니다.')

결과는 0.87 입니다
사인값은 양수입니다.


In [ ]:

x = 1
y = -2

place = 0
if y > 0:
  if x > 0:
    place = 1
  elif x < 0:
    place = 2
elif y < 0:
  if x < 0:
    place = 3
  elif x > 0:
    place = 4

if place==0:
  print('점이 축 위에 있습니다.')
else:
  print(f'점은 {place}사분면에 있습니다.')

점은 4사분면에 있습니다.


In [ ]:
score = 85
if score >= 90:
  print('A')
elif score >= 80:
  print('B')
elif score >= 70:
  print('C')
elif score >= 60:
  print('D')
else:
  print('F')

B


In [ ]:
weight = 65.3
height = 1.74

bmi = weight / (height * height) #bmi의 계산
if bmi >= 25:
  print('비만')
elif bmi < 18.5:
  print('저체중')
else:
  print('정상')

정상


In [ ]:
number_of_purchases = 10
total_amount_of_purchases = 150000
price_item = 5000
membership = 0

if number_of_purchases >= 10 and total_amount_of_purchases >= 100000:
  membership = 1

if membership == 1:
  price_item = price_item * 0.9

if membership == 0 and number_of_purchases >= 1:
  price_item = price_item * 0.95

print(f'고객님의 실구매 가격은 {int(price_item)}원입니다.')

고객님의 실구매 가격은 4500원입니다.


In [ ]:
a = 93
b = 64
c = 65
d = 68

if a < 60 or b < 60 or c < 60 or d < 60 or (a+b+c+d)/4 <= 70:
  print('불합격입니다.')
else:
  print('합격입니다.')
  

합격입니다.


In [ ]:
vs = [3, 'hi', 8.5, 999, 1, 3, 'hi', 53]

In [ ]:
vt = vs

In [ ]:
vt[3] = -5

In [ ]:
print(vt)

[3, 'hi', 8.5, -5, 1, 3, 'hi', 53]


In [ ]:
a = range(3)

In [ ]:
list(a)

[0, 1, 2]

In [ ]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [ ]:
a = (3,4,5)

In [ ]:
b = list(a)

In [ ]:
print(a)
print(b)

(3, 4, 5)
[3, 4, 5]


In [ ]:
b[2] = 10

In [ ]:
print(a)
print(b)

(3, 4, 5)
[3, 4, 10]


In [ ]:
d1 = {'Title':'The Chronics of Naria',
      'year':1950,
      'Author': 'C.S. Lewis',
      'Country':'UK',
      'Genere':'Fantasy'
      }

In [ ]:
d2 = {'Title':'Harry Potter',
      'year': 1990,
      'Author': 'J.K. Rowling',
      'Country':'UK',
      'Genere':'Fantasy'
      }

d3 = {'Title':'Stop Talking, Start Influencing: 12 Insights from Brain Science to Make Your Message Stick',
      'year':2020,
      'Author': 'Jared Cooney Horvath',
      'Country':'USA',
      'Genere':'Self-development'
      }

In [ ]:
d_list= [d1,d2,d3]

In [ ]:
d2['Country']

'UK'

In [ ]:
v = [3,4,5,6]

In [ ]:
avg = (v[0]+v[1]+v[2]+v[3])/4

In [ ]:
v = list(range(1,30,2))
print(v[14])

29


In [ ]:
dict1 = {'korean': '사랑', 'English': 'LOVE', 'Japanese': '愛'}

In [ ]:
dict_list = []

dict_list.append({'korean': '사랑', 'English': 'LOVE', 'Japanese': '愛'})
dict_list.append({'korean': '믿음', 'English': 'Faith', 'Japanese': '信'})
dict_list.append({'korean': '소망', 'English': 'Hope', 'Japanese': '愛'})
dict_list.append({'korean': '행복', 'English': 'Happiness', 'Japanese': '愛'})

print(dict_list)

[{'korean': '사랑', 'English': 'LOVE', 'Japanese': '愛'}, {'korean': '믿음', 'English': 'Faith', 'Japanese': '信'}, {'korean': '소망', 'English': 'Hope', 'Japanese': '愛'}, {'korean': '행복', 'English': 'Happiness', 'Japanese': '愛'}]


In [ ]:
for x in range(1,6):
  print(x)

1
2
3
4
5


In [ ]:
x_list = [3,4,5,6,7,8]
for x in x_list:
  print(x)

3
4
5
6
7
8


In [ ]:
n=17
m=0
print(n)
while n != 1:
  if n%2 ==0:
    n = n/2
  else:
    n = n *3+1
  print(n)
  m = m+1
print(f'콜라츠 추측이 {m}번만에 성립함이 확인되었습니다.')

17
52
26.0
13.0
40.0
20.0
10.0
5.0
16.0
8.0
4.0
2.0
1.0
콜라츠 추측이 12번만에 성립함이 확인되었습니다.


In [ ]:
v = [3,4,5,6]

In [ ]:
sum = 0
for x in v:
  sum += x
avg = sum/len(v)

In [ ]:
print(avg)

4.5


In [ ]:
n = 0
power_of_n = 1

while power_of_n <= 10000:
  n += 1
  power_of_n *= 2

print(f'The answer is {int(power_of_n/2)}')

The answer is 8192


In [ ]:
import numpy as np
#n = np.array([[3,4,1,2],[8,2,4,9]])
n_list = [[3,4,1,2],[8,2,4,9]]
n = np.array(n_list)

In [ ]:
n_list[0][2]

1

In [ ]:
n[0,2]

1

In [ ]:
n = np.ones((3,5))

In [ ]:
n[2,4]=100

In [ ]:
n = np.random.rand(3,5)

In [ ]:
n

array([[0.36523762, 0.91487637, 0.78054645, 0.10730295, 0.42194033],
       [0.60146388, 0.77234832, 0.80836079, 0.64799688, 0.1533315 ],
       [0.80454395, 0.37053734, 0.45067463, 0.81919466, 0.05927802]])

In [ ]:
n = np.round(n*10)

In [ ]:
n

array([[4., 9., 8., 1., 4.],
       [6., 8., 8., 6., 2.],
       [8., 4., 5., 8., 1.]])

In [ ]:
n[:,::2]

array([[4., 8., 4.],
       [6., 8., 2.],
       [8., 5., 1.]])

In [ ]:
b= np.array([[True, False, True, False, True],
             [True, False, True, False, True],
             [True, False, True, True, False]])

In [ ]:
n[b] = 0

In [ ]:
b = n>3

In [ ]:
b

array([[False,  True, False, False, False],
       [False,  True, False,  True, False],
       [False,  True, False, False, False]])

In [ ]:
n[b] = 10

In [ ]:
n

array([[ 0., 10.,  0.,  1.,  0.],
       [ 0., 10.,  0., 10.,  0.],
       [ 0., 10.,  0.,  0.,  1.]])

In [ ]:
import numpy as np
x = 0 #큰 수를 저장할 변수
i = 0 #loop변수
j = 0
while i < 20000:
  n = 5*i**3+2*i**2-19*i+20
  if(n>x):
    x = n;
    j = i
  i += 1
print(x)
print(j)

39994799840036
19999


In [ ]:
lot_answer = list([3,5,14,16,36,38])
lot_me = list([3,7,13,16,35,38])
count = 0

for i in range(0,6):
  if lot_answer[i] == lot_me[i]:
    count += 1
print(count)


3


In [ ]:
import numpy as np

n = np.round(np.random.rand(3,4)*10,0)

In [ ]:
n

array([[3., 2., 2., 6.],
       [8., 8., 2., 7.],
       [2., 4., 3., 3.]])

In [ ]:
n.shape

(3, 4)

In [ ]:
m=n.reshape(12)

In [ ]:
m

array([3., 2., 2., 6., 8., 8., 2., 7., 2., 4., 3., 3.])

In [ ]:
k = m.reshape(2, 3,-1)

In [ ]:
m = np.expand_dims(n,-1)

In [ ]:
k.shape

(2, 3, 2)

In [ ]:
m

array([3., 2., 2., 6., 8., 8., 2., 7., 2., 4., 3., 3.])

In [ ]:
n.std()

2.3033791601808757

In [ ]:
data = np.array([[8.5, 200, 60.2, 450.3, 50],
                 [12.3, 230.5, 56.3, 390.2, 35],
                 [9.2, 190, 30, 500.4, 60]])

mean_v = np.mean(data, axis=0)
std_v = np.std(data, axis=0)
print(f'50m달리기: {mean_v[0]:.2f}±{std_v[0]:.2f}')
print(f'멀리뛰기: {mean_v[1]:.2f}±{std_v[1]:.2f}')
print(f'오래매달리기: {mean_v[2]:.2f}±{std_v[2]:.2f}')
print(f'오래달리기: {mean_v[3]:.2f}±{std_v[3]:.2f}')
print(f'윗몸일으키기: {mean_v[4]:.2f}±{std_v[4]:.2f}')

50m달리기: 10.00±1.65
멀리뛰기: 206.83±17.23
오래매달리기: 48.83±13.41
오래달리기: 446.97±45.05
윗몸일으키기: 48.33±10.27


In [ ]:
data = np.array([1,2,5,0,1])
idx_max = np.argmax(data)
idx_min = np.argmin(data)
print(f'최솟값은 {data[idx_min]} 입니다.')
print(f'최댓값은 {data[idx_max]} 입니다.')

최솟값은 0 입니다.
최댓값은 5 입니다.


In [ ]:
data = np.array([[8.5, 200, 60.2, 450.3, 50],
                 [12.3, 230.5, 56.3, 390.2, 35],
                 [9.2, 190, 30, 500.4, 60]])

In [ ]:
data_sel = data[data[:,1]>190,:]

In [ ]:
data_sel

array([[  8.5, 200. ,  60.2, 450.3,  50. ],
       [ 12.3, 230.5,  56.3, 390.2,  35. ]])

In [ ]:
data.min(0)

array([  8.5, 190. ,  30. , 390.2,  35. ])

In [ ]:
idx_min = np.argmin(data, axis=0)

In [ ]:
best_50m_idx = idx_min[0]
long_jump_of_best_50m_person = data[best_50m_idx, 1]

In [ ]:
long_jump_of_best_50m_person

200.0

In [ ]:
n = np.random.rand(45)

In [ ]:
np.shape(n)

(45,)

In [ ]:
n = n.reshape(9,5)

In [ ]:
np.shape(n)

(9, 5)

In [ ]:
n = np.expand_dims(n,-1)

In [ ]:
np.shape(n)

(9, 5, 1)

In [ ]:
n

array([[[0.197498  ],
        [0.40965635],
        [0.50791313],
        [0.00863211],
        [0.22048321]],

       [[0.84732371],
        [0.64455982],
        [0.61800516],
        [0.0509454 ],
        [0.08528525]],

       [[0.28615367],
        [0.97211481],
        [0.01317919],
        [0.72642753],
        [0.41224598]],

       [[0.10115937],
        [0.9388051 ],
        [0.59581212],
        [0.52609129],
        [0.23207247]],

       [[0.03918042],
        [0.80800647],
        [0.83590049],
        [0.76490056],
        [0.73107929]],

       [[0.51974488],
        [0.26422363],
        [0.82912577],
        [0.45889035],
        [0.8197879 ]],

       [[0.9165849 ],
        [0.20047719],
        [0.64627747],
        [0.71335433],
        [0.65428685]],

       [[0.92871606],
        [0.31971873],
        [0.87667928],
        [0.0296932 ],
        [0.65845037]],

       [[0.12723423],
        [0.40048599],
        [0.27082052],
        [0.65615677],
        [0.94146

In [ ]:
data = np.array([[8.5, 200, 60.2, 450.3, 50],
                 [12.3, 230.5, 56.3, 390.2, 35],
                 [9.2, 190, 30, 500.4, 60]])

In [ ]:
data_sel = data[data[:,2]>=40, :]

In [ ]:
data_sel[:,4].mean()

42.5

In [ ]:
data

array([[  8.5, 200. ,  60.2, 450.3,  50. ],
       [ 12.3, 230.5,  56.3, 390.2,  35. ],
       [  9.2, 190. ,  30. , 500.4,  60. ]])

In [ ]:
data[data[:,3]>400,3] = 400

In [1]:
data

NameError: ignored

In [6]:
def add(v1, v2=5):
  sum = v1 + v2
  return sum

v = add(3)
print(v)

8


In [16]:
def add():
  s = a + b + d
  return s

a = 4
b = 5
c = add()
d = 4
print(c)

NameError: ignored

In [19]:
import numpy as np

def change_var(arr):
  arr[0,0] = 999

d = np.random.rand(5,4)
print(f'함수호출 전: {d[0,0]}')
change_var(d)
print(f'함수호출 후: {d[0,0]}')

함수호출 전: 0.3519074008812876
함수호출 후: 999.0


In [35]:
import numpy as np

def every_step(step):
 return np.mean(step), np.argmin(step), np.min(step), np.argmax(step), np.max(step)
 

n = np.round(np.random.rand(30)*3000,0)
print(n)

step_mean, step_argmin, step_min, step_argmax, step_max = every_step(n)

print(step_mean, step_argmin+1, step_min, step_argmax+1, step_max)

[ 720.  225. 2106. 1339. 2685.  532. 2614. 2071.  154. 1757. 2480.  928.
 1773.  881. 2360. 2666. 1564. 2973. 2539.  862. 1196. 1374.  439.   67.
 2112. 2223. 2476.  157.   57.  620.]
1465.0 29 57.0 18 2973.0


In [ ]:
from google.colab import drive
drive.mount('/content/drive')