In [3]:
from google.colab import files
from google.colab import drive

files.upload()
!mkdir ~/.kaggle
!mv kaggle.json ~/.kaggle
!chmod 600 ~/.kaggle/*
drive.mount('/content/gdrive')

Saving kaggle.json to kaggle (1).json
mkdir: cannot create directory ‘/root/.kaggle’: File exists
Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [4]:
!kaggle competitions list

ref                                                                                deadline             category             reward  teamCount  userHasEntered  
---------------------------------------------------------------------------------  -------------------  ---------------  ----------  ---------  --------------  
https://www.kaggle.com/competitions/vesuvius-challenge-ink-detection               2023-06-14 23:59:00  Featured         $1,000,000        323           False  
https://www.kaggle.com/competitions/asl-signs                                      2023-05-01 23:59:00  Research           $100,000        856            True  
https://www.kaggle.com/competitions/tlvmc-parkinsons-freezing-gait-prediction      2023-06-08 23:59:00  Research           $100,000        364           False  
https://www.kaggle.com/competitions/amp-parkinsons-disease-progression-prediction  2023-05-18 23:59:00  Featured            $60,000        992           False  
https://www.kaggle.com/competition

In [17]:
cd '/content/gdrive/MyDrive/Colab Notebooks/titanic'

/content/gdrive/MyDrive/Colab Notebooks/titanic


In [19]:
ls

gender_submission.csv  test.csv  test_predict.csv  titanic.zip  train.csv


In [45]:
import pandas as pd
!kaggle competitions download -c titanic

data_train = pd.read_csv('train.csv')
data_test = pd.read_csv('test.csv')

titanic.zip: Skipping, found more recently modified local copy (use --force to force download)


In [41]:
import numpy as np
data_len = data_train.shape[0]
data_train_np = np.zeros([data_len ,8])

In [46]:
data_train_np

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [50]:
data_train['Sex'] == 'female'

0      False
1       True
2       True
3       True
4      False
       ...  
886    False
887     True
888     True
889    False
890    False
Name: Sex, Length: 891, dtype: bool

In [66]:
cnt = 0
sex_num = np.zeros(data_train_np.shape[0])
sex_num[np.array(data_train['Sex']=='female')]=1

In [67]:
sex_num

array([0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 0.,
       0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0.,
       0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0.,
       1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 0.

In [70]:
from tensorflow.keras.utils import to_categorical
data_train_np[:,0:2] = to_categorical(sex_num)

In [72]:
data_train_np[:,2:5] = to_categorical(data_train['Pclass'].to_numpy()-1)

In [73]:
data_train_np[:,5] = data_train['Age']/80
data_train_np[:,6] = data_train['SibSp']/10
data_train_np[:,7] = data_train['Parch']/10

In [78]:
print(data_train_np[:,5])

[0.275    0.475    0.325    0.4375   0.4375        nan 0.675    0.025
 0.3375   0.175    0.05     0.725    0.25     0.4875   0.175    0.6875
 0.025         nan 0.3875        nan 0.4375   0.425    0.1875   0.35
 0.1      0.475         nan 0.2375        nan      nan 0.5           nan
      nan 0.825    0.35     0.525         nan 0.2625   0.225    0.175
 0.5      0.3375        nan 0.0375   0.2375        nan      nan      nan
      nan 0.225    0.0875   0.2625   0.6125   0.3625   0.8125        nan
 0.2625   0.35625  0.0625   0.1375   0.275    0.475    0.5625   0.05
      nan      nan 0.3625   0.2375   0.2125   0.325    0.4      0.2
 0.2625   0.325    0.4      0.3125        nan      nan 0.010375 0.375
 0.275    0.3625        nan 0.35     0.2125   0.4125   0.2           nan
 0.2875   0.3      0.3625   0.25     0.575    0.325    0.7375        nan
 0.8875   0.2875   0.425    0.425    0.35          nan 0.2625   0.4125
 0.4625   0.35     0.2625        nan 0.475         nan 0.5875   0.18125
 0.27

In [88]:
np.sum(np.isnan(data_train_np))

0

In [86]:
data_train_np[np.isnan(data_train_np[:,5]),5] = 30/80

In [91]:
data_train_np[5,:]

array([1.   , 0.   , 0.   , 0.   , 1.   , 0.375, 0.   , 0.   ])

In [92]:
data_train_np_y = to_categorical(data_train['Survived'])

In [93]:
data_train_np_y

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]], dtype=float32)